### ISSUE TITLE
Clean UP & Dockerization eos4q1a

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4q1a#12]

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
The model is working fine without refactoring with `run.sh`, generates upto 100 molecules for each small molecule or smile but when i tested it with Ersilia using` --repo-path`, it shows all the generated output as a list in a single column. For the review i'm attaching the output i get with `run.sh` and with `--repo-path`


[output_repo_path.csv](https://github.com/ersilia-os/eos4q1a/files/12176526/output_repo_path.csv)
[output_run.sh.csv](https://github.com/ersilia-os/eos4q1a/files/12176525/output_run.sh.csv)

So, this mean there is some problem in service.py as run.sh is giving the output fine. I tried to figure it out and it seems the problem is here

```
            for r in reader:
                R += [{"outcome": [String(x) for x in r]}]
        meta = {
            "outcome": h
        }
```
I have tried different things to make it work. Like i have tried following changes as well but it still shows the generated molecules in single column as a list but this time it shows it as a outcome_0, outcome_1 and so on

```
            for r in reader:
                row_data = {}
                for i, x in enumerate(r):
                    row_data[f"outcome_{i}"] = x
                R.append(row_data)
        meta = {
            "outcome": h
        }
```
and the output is attached here


[eos4q1a_new_output.csv](https://github.com/ersilia-os/eos4q1a/files/12176643/eos4q1a_new_output.csv)


Still i couldn't able to fix it properly so it shows separate columns for each of the generated molecules against a smile input. Working on it.
Thanks

**Comment by carcablop** [comment]
Hello @ZakiaYahya 

What you see in this model's output occurs because the model's output shape is a '_flexible list_'. 
In the output.py, in the `to_dataframe` function, which is executed when the output that we specify is a csv, in this line of code: [https://github.com/ersilia-os/ersilia/blob/master/ersilia/io/output.py#L238](https://github.com/ersilia-os/ersilia/blob/master/ersilia/io/output.py#L238)  when the output shape of a model is equal to a flexible list, the output is in a single column '**outcome**' of the csv file.

**Comment by ZakiaYahya** [comment]
Oh Alright @carcablop 
Many Thanks for pointing it out, i've never thought of it. 
Yes, the output shape is `flexible list` but i was getting separate neat and clean columns with `run.sh`, which i didn't get with `repo-path`. So, i thought to make some changes in `service.py `but whatever i did, it still comes out as single _outcome_ column. Now i got it, why it behaving like this because it is defined in Ersilia codespace. I think then i just make a little bit change that it just shows `outcome_0`, `outcome_1`  and so on at the start of each generated molecule, So the user can easily get to know how many molecules are generated against a specific small molecule.

Thanks

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

Thanks for the work and detailed explanations. In this case, it is best if we leave the output of the flexible list as a dictionary with only one key, outcome, and a list of SMILES as values. This way, if we ever want to refactor how these outputs are handled, as @carcablop mentions, we will be able to work at the Ersilia level rather than model by model. I hope this makes sense!

**Comment by ZakiaYahya** [comment]
Alright @GemmaTuron 
Then i think, i'll leave the output as it is and just go for refactoring and open PR on it.
Thanks

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
I've open PR on it.
Thanks
